In [1]:
import numpy as np

In [4]:
!pip install numpy

In [12]:
##create array using numpy
## create a 1D array
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [21]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)   ## 1 row and 5 cols

array([[1, 2, 3, 4, 5]])

In [28]:
arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [36]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [39]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [40]:
## identity matrix 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [46]:
## Attributes of Numpy

arr = np.array([[1,2,3],[2,3,4],[3,4,5]])

print("Array:", arr)
print("Shape:", arr.shape)
print("Number of dimensions:", arr.ndim)
print("Size(number  of elements):", arr.size)
print("Data type:", arr.dtype)
print("Item size (in bytes):", arr.itemsize)

Array: [[1 2 3]
 [2 3 4]
 [3 4 5]]
Shape: (3, 3)
Number of dimensions: 2
Size(number  of elements): 9
Data type: int64
Item size (in bytes): 8


In [52]:
## Numpy vectorized operations

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

## Element wise addition
print("Addition:", arr1+arr2)

## Element wise substraction 
print("Substraction:", arr1-arr2)

## Element wise multiplication 
print("multiplication:", arr1*arr2)

## Element wise division
print("Division:", arr1/arr2)

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [57]:
## Universal function
arr = np.array([1,2,3,4,5])

## square root
print("square root:", np.sqrt(arr))

## Exponential
print("Exponential:", np.exp(arr))

## Sine
print("Sine:", np.sin(arr))

## Cos
print("Cos:", np.cos(arr))

## Log
print("Log:", np.log(arr))

square root: [1.         1.41421356 1.73205081 2.         2.23606798]
Exponential: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Sine: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Cos: [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
Log: [0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [100]:
## array slicing and indexing
arr = np.array([[1,2,3,4],[5,6,7,8],[9,19,11,12]])
print("Array: \n", arr)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 19 11 12]]


In [67]:
print("1st row:", arr[0])
print("2nd row:", arr[1])
print("3rd row:", arr[2])
print("1st row 1st element:", arr[0][0])
print("1st row 2nd element:", arr[0][1])
print("1st row 3rd element:", arr[0][2])
print("2nd row 1st element:", arr[1][0])


1st row: [1 2 3 4]
2nd row: [5 6 7 8]
3rd row: [ 9 19 11 12]
1st row 1st element: 1
1st row 2nd element: 2
1st row 3rd element: 3
2nd row 1st element: 5


In [72]:
## extract elements 7,8,11,12 
## understand those are in which row 
## available in 2nd and 3rd row 

arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [96]:
arr[0:2,2:]

array([[3, 4],
       [7, 8]])

In [97]:
arr[1:]

array([[ 5,  6,  7,  8],
       [ 9, 19, 11, 12]])

In [99]:
arr[1:3]

array([[ 5,  6,  7,  8],
       [ 9, 19, 11, 12]])